
no_display = False
silent = False
file_loop = False
perf_data = None

MAX_DISPLAY_LEN=64
PGIE_CLASS_ID_VEHICLE = 0
PGIE_CLASS_ID_BICYCLE = 1
PGIE_CLASS_ID_PERSON = 2
PGIE_CLASS_ID_ROADSIGN = 3
MUXER_OUTPUT_WIDTH=1920
MUXER_OUTPUT_HEIGHT=1080
MUXER_BATCH_TIMEOUT_USEC=4000000
TILED_OUTPUT_WIDTH=1280
TILED_OUTPUT_HEIGHT=720
GST_CAPS_FEATURES_NVMM="memory:NVMM"
OSD_PROCESS_MODE= 0
OSD_DISPLAY_TEXT= 1

YOLO_PLUGIN_LIB = "/opt/models/yolov7/libmyplugins.so"
YOLO_CONFIG = "config/config_yolov5.txt"

RETINAFACE_PLUGIN_LIB = '/opt/models/retinaface/libdecodeplugin.so'
RETINAFACE_CONFIG = "config/config_retinaface.txt"